Feature/axiomapy 38
Qontigo/axioma-py pull request #25
Opened 2023-05-09 19:29 UTC by shans-qontigo

Changes as part of PR:
1. Default Client id
2. Axiomapy endpoint mapping doc
3. updated examples for client id
4. Updated docs

2023-06-13 01:17 UTC, wdeng-qontigo approved these changes

2023-06-14 21:20 UTC, lswift-qontigo commented on CHANGELOG.rst
Is the wording correct here? Should it be: 

The AxiomaSession initiation will now only require username, password, and domain.

2023-06-14 21:48 UTC, lswift-qontigo reviewed
A few minor comments around wordings. As discussed on teams it might also be nice to explicitly mention in any failed use/get session method call the details of the changes that have been made. Just an error message saying something like: unable to authenticate a session, please note that release xx.xxx contained a breaking change to the use/get session method by making client id an optional field, please see change log/examples for further details of this change....

2023-06-14 21:48 UTC, lswift-qontigo commented on axiomapy/examples/getting_started.ipynb
Is pandas listed in the dependencies file?

2023-06-14 21:48 UTC, lswift-qontigo commented on axiomapy/examples/getting_started.py
I suspect that some clients will still want to provide their own client id in some cases. It would be good to add an example overriding the clientid too.

2023-06-14 21:48 UTC, lswift-qontigo commented on axiomapy/examples/getting_started.py
The #Create a portfolio if it doesn't exist already example seems to try to create a portfolio, then if it fails print the portfolio id. Would it be a better example to run a get first and in the case nothing is returned attempt to create the portfolio? Just a comment, not necessary.

2023-06-14 21:48 UTC, lswift-qontigo commented on axiomapy/examples/getting_started.py
The comment:
#The results can be accessed in the json format
seems to refer to an example which is getting logs not results

2023-06-14 21:48 UTC, lswift-qontigo commented on axiomapy/examples/getting_started.py
Adding to the previous comment I think the following would be better:
#The log file for a particular analysis job can be fetched in a json format
logs = AnalysesRiskAPI.get_analyses_log(requestId)
print(logs.json())


#The results can be accessed in the json format
results = AnalysesRiskAPI.get_analyses(requestId).json()
print(results)

#The results can also be fetched in a csv format
results = AnalysesRiskAPI.get_analyses(requestId, as_csv=True).text
print(results)
df = pd.read_csv(StringIO(results), delimiter=',')

2023-06-14 22:19 UTC, hzeng-qontigo commented on axiomapy/examples/getting_started.py
> The #Create a portfolio if it doesn't exist already example seems to try to create a portfolio, then if it fails print the portfolio id. Would it be a better example to run a get first and in the case nothing is returned attempt to create the portfolio? Just a comment, not necessary.

This is deliberate, to demonstrate use of axioma exceptions.

2023-06-14 22:22 UTC, hzeng-qontigo commented on axiomapy/examples/getting_started.py
> I suspect that some clients will still want to provide their own client id in some cases. It would be good to add an example overriding the clientid too.

Agreed.  @shans-qontigo , this would be helpful

2023-06-14 22:23 UTC, hzeng-qontigo requested changes
Please can we add an example of clientid override, as suggested by Luke?

2023-07-07 13:55 UTC, hzeng-qontigo approved these changes

2023-07-07 13:57 UTC, lswift-qontigo approved these changes

2023-07-07 16:36 UTC, merged