updates to accept zip input format for Bulk endpoint
Qontigo/axioma-py pull request #36
Opened 2024-06-25 16:02 UTC by shans-qontigo

Updates to accept zip input format for Bulk endpoint:
1. Updated bulk.py - to add additional headers
2. Updates session.py as currently is accepts only json input

2024-06-26 08:04 UTC, lswift-qontigo requested changes
On the face of it the changes look ok however, I don't think that compressed payloads are unique to the bulk api. I am wondering whether we would want to make the change in the actual session class instead of isolating the change to the bulk api.

2024-06-26 20:15 UTC, wdeng-qontigo commented on axiomapy/axiomaapi/bulk.py
> +            payload,
type for "payload" is missing

2024-06-26 20:16 UTC, wdeng-qontigo commented on axiomapy/session.py
> +        data = None,
type for "data"?

2024-06-26 20:16 UTC, wdeng-qontigo commented on axiomapy/session.py
> +        data = None,
type of "data"?

2024-06-26 20:58 UTC, shans-qontigo commented on axiomapy/axiomaapi/bulk.py
> +            payload,
Added!

2024-06-26 20:59 UTC, shans-qontigo commented on axiomapy/session.py
> +        data = None,
Added

2024-07-11 17:27 UTC, lswift-qontigo approved these changes

2024-07-11 21:48 UTC, bspector-qontigo approved these changes

2024-07-11 23:58 UTC, wdeng-qontigo approved these changes

2024-07-12 14:56 UTC, merged